<?php 

$programing = array();
	foreach ($variable as $key => $value) 
	{
		Rapid Application Development (RAD) sebagai salah satu alternatif dari System Development Life Cycle belakangan ini seringkali guna untuk atas lambat yang terjadi apabila guna metode konvensional. Adapun unggul yang bisa didapatkan dengan guna metode ini adalah cepat, tepat, dan biaya yang relatif lebih rendah dibanding dengan metode konvensional. Di samping itu dengan melibatkan user pada proses desain menyebabkan kebutuhan user dapat terpenuhi dengan baik dan secara otomatis kepuasan user sebagai pengguna sistem semakin meningkat. Akan tetapi di dalam guna metode Rapid Aplication Development perlu untuk memperhatikan hal-hal yang penting, terutama kesiapan tim, ruang lingkup sistem, kebutuhan user, dan kinerja sistem. Pada akhirnya, sebagai salah satu alternatif dari System Development Life Cycle, maka Rapid Aplication Development dapat dijadikan acuan untuk menghasilkan sistem informasi yang dapat memenuhi kebutuhan user.

		sistem pendukung keputusan yang dapat menganalisa beberapa karyawan yang sesuai dengan profil jabatan yang ada. Sistem pendukung keputusan untuk proses profile matching dan analisis gap ini dibuat berdasarkan data dan norma-norma SDM. Proses Profile Matching dilakukan untuk menentukan rekomendasi karyawan dalam Sistem Kenaikan Jabatan dan Perencanaan Karir berdasar pada 3 aspek yaitu Kapasitas Intelektual, Sikap Kerja dan Perilaku. Hasil dari proses ini berupa ranking karyawan sebagai rekomendasi bagi pengambil keputusan untuk memilih karyawan yang cocok pada jabatan yang kosong tersebut. Software ini dibuat dengan guna Microsoft Access 2000 untuk database dan Borland Delphi 5 sebagai compiller-nya. Dari hasil implementasi sistem, disimpulkan bahwa dengan penggunaan software ini dapat membantu proses pengambilan keputusan terhadap profile matching proses kenaikan jabatan dan perencanaan karir 

		Banyak teori dan pendekatan yang dikembangkan untuk memperoleh hasil penemuan kaidah asosiasi dan pola. Salah satu metode yang dikembangkan yaitu dengan guna metode apriori. Beberapa dari metode sebelumnya melakukan pencarian itemset dengan pendekatan graf asosiasi yang memiliki kelemahan pada penggunaan memori yang besar. Keterbatasan memori jelas akan mempengaruhi banyaknya item yang bisa diproses. Lebih jauh lagi, sebagian besar pendekatan guna struktur data internal sangat rumit yang tidak bersifat lokal dan membutuhkan tambahan sumber daya dan banyak komputasi. Pada riset ini, metode apriori guna untuk memperoleh kaidah asosiasi yang menggambarkan hubungan antar item pada database transaksional. Database yang guna ada tiga buah yang masing-masing memiliki jumlah transaksi yang berbeda. Dari hasil pengujian empiris dapat ditarik kesimpulan bahwa waktu komputasi untuk menghasilkan kaidah asosiasi dipengaruhi oleh jumlah transaksi dan Penggunaan struktur data tidlist pada algoritma apriori menyebabkan waktu komputasi yang dibutuhkan relatif berkurang karena hanya memerlukan pembacaan basis data sekali saja.

		Untuk menentukan tingkat kualitas kesejahteraan masyarakat Desa Kutawaringin dapat dilakukan survey guna Sistem Penunjang Keputusan  berbasis web dengan indikator yang telah di tetapkan oleh Badan Koordinasi Keluarga Berencana Nasional. Metode penelitian yang guna dalam tahap pengumpulan data adalah observasi, wawancara dan pustaka. Sistem berisi tentang halaman index, halaman tampil, halaman login, dan halaman quisioner. Sistem dirancang dengan PHP sebagai bahasa pemrograman pengkoneksi database, MySQL sebagai database, Macromedia Dreamweaver untuk perancangan web, Jquery Mobile Framework untuk perancangan web mobile dan Apache sebagai server web. Implementasi sistem yang di rancang guna model prototyping. Sistem Penunjang Keputusan berbasis web dapat membantu penilaian kualitas kesejahteraan masyarakat dengan cepat. Augmented Reality (AR) adalah sebuah teknik dalam bidang ilmu komputer yang mengkombinasikan antara kondisi dunia nyata dengan data hasil komputasi dari sebuah komputer dalam bentuk grafis 2D maupun 3D. Pada penelitian ini, dibahas sebuah metode dan implementasi aplikasi di lingkungan Augmented Reality secara markerless. Pada metode markerless proses interaksi antara manusia dan komputer lebih alami dan intuitif dibandingkan dengan metode berbasis marker. Metode markerless yang diterapkan pada penelitian ini guna titik-titik fitur wajah supaya hasilnya lebih robust karena objek kepala tidak menghasilkan cahaya sehingga mengandalkan titik-titik fitur wajah. Permasalahan utama pada bidang penelitian ini adalah bagaimana proses pengontrolan pergerakan objek 3D tersebut tidak mengalami anomali seperti rel kereta api, semakin jauh mata memandang seakan-akan jarak antara kedua rel kereta api semakin menyempit. Penelitian ini guna metode POSIT (Pose from Ortography and Scale with ITeration), posisi dan orientasi objek 3D diproyeksikan secara ortografi dari titik-titik fitur wajah dengan pen-skalaan, sehingga perubahan jarak antara wajah dan webcam berbanding lurus dengan perubahan besar dan kecilnya objek 3D. Langkah berikutnya dilakukan proses iterasi  empat sampai lima kali untuk mencari faktor kesalahan terkecil sehingga didapatkan pose terbaik.   Kata Kunci— Augmented Reality, Titik Fitur Wajah, POSIT,      Objek 3D 

		Perkembangan jaman memiliki dampak yang cukup besar terhadap keberadaan suatu bahasa. Untuk atas hal itu ada beberapa upaya yang dapat dilakukan, salah satunya adalah dengan membuat kamus, kamus yang di buat haruslah praktis dan cepat dalam penggunaanya. Kamus yang dimaksud adalah kamus berbasis android. Untuk membuat kamus berbasis android dapat guna algoritma string matching, salah satu algoritma string matching adalah algoritma Rabin-Karp, algoritma Rabin-Karp melakukan pencocokan string berdasarkan nilai hash pada teks dan nilai hash pada pattern. Penelitian ini menghasilkan sebuah aplikasi kamus berbasis android  yang mana bilangan basis yang guna untuk membangkitkan nilai hash sangat mempengaruhi cepat pencarian kata. Rata-Rata running time untuk untuk 10 kali percobaan pencarian kata adalah 14.9 ms. Kata Kunci : Android, Kamus, Rabin-Karp, String Matching 

		Teknologi semakin hari semakin berkembang pesat mengikuti alur modernisasi pada masa kini. Teknologi deteksi wajah adalah salah satu teknologi yang banyak dikembangkan dan diaplikasikan dalam berbagai sektor seperti sistem pengenalan biomatrik, sistem pencarian, pengindeksan pada database video digital, sistem keamanan kontrol akses area terbatas, konferensi video, dan interaksi manusia dengan komputer. Dari berbagai sektor yang bisa dikembangkan, muncul ide baru untuk mengaplikasikan citra digital hasil deteksi wajah lebih lanjut, yaitu deteksi mata (eye detection). Deteksi mata merupakan pengembangan lanjut dari deteksi wajah dimana citra wajah manusia yang berhasil dideteksi akan diproses kembali dengan mendeteksi letak kedua mata pada wajah tersebut.   Aplikasi Eye Detection ini dibangun dengan bahasa pemrograman Java Android yang dijalankan melalui sebuah perangkat Android. Dengan memanfaatkan sistem OpenCV dan sumber kode face detection yang sudah ada sebelumnya. melalui beberapa cara fase pengembangan sistem untuk dijadikan sebuah aplikasi face detection. Dengan adanya Aplikasi Deteksi Mata untuk perangkat android ini dapat guna sebagai sarana pengembangan Aplikasi Deteksi Mata yang lebih kompleks dan bisa diterapkan secara langsung dalam aspek teknologi yang guna Deteksi Mata, sepeti sistem penunjang keamanan berkendara, aplikasi deteksi penyakit lewat mata, dan aplikasi penunjang deteksi identitas manusia lewat mata.   Kata Kunci : eye detection, OpenCV, Deteksi Mata, Image Processing  

		Self Constructing Fuzzy Neural Network (SCFNN) guna sebagai metode pengambilan keputusan dalam mengindentifikasi dan tracking obyek wajah yang diimplementasikan pada robot manipulator 2 derajat kebebasan, yaitu gerakan arah memutar pada sumbu X, perputaran terhadap sumbu Y dan berhenti. Keuntungan dari penggunaan metode SCFNN adalah tidak perlu menginisialisasi rule, konvergen secara cepat dan presisi. SCFNN diusulkan sebagai perbaikan hasil dari penggunaan ANN dan Fuzzy Logic Control, karena SCFNN merupakan penggabungan dari kelebihan kedua metode tersebut. Kontrol SCFNN guna sebagai tahap akhir dari sistem tracking obyek yang diambil berdasarkan proses citra wajah yaitu besar error yang terjadi berdasarkan posisi wajah yang terdeteksi terhadap titik tengah kamera. Berdasarkan hasil pengujian sistem steady state error rata-rata pada proses tracking dengan posisi obyek yang berbeda adalah sebesar 1,4 pixel untuk gerakan kearah sumbu x dan 1,2 pixel untuk arah sumbu y dan overshoot sebesar 0%, serta settling time sebesar 1,66 detik hingga 1,72 detik.  Kata Kunci:  Control SCFNN, Deteksi wajah, robot 2 DOF 

		Kebutuhan  akan  sistem  informasi  agenda  diperlukan  bagi  Badan Pelayanan Perizinan Terpadu (BPPT) Kabupaten Karanganyar dalam mengolah penggagendaan surat masuk dan surat keluar, berdasarkan  alasan  tersebut  maka  dibuat aplikasi  sistem  informasi  manajemen agenda yang  dapat  membantu mempermudah mengolah surat masuk dan surat keluar. Pada Badan Pelayanan Perizinan Terpadu (BPPT) Kabupaten Karanganyar, surat merupakan sarana penting, informasi-informasi penting dan rahasia terkait dengan instansi tersebut terkandung di dalamnya.  Pada saat ini, prosedur yang diterapkan pada manajemen surat masuk dan surat keluar pada Badan Pelayanan Perizinan Terpadu (BPPT) Kabupaten Karanganyar mulai dari penerimaan, pembuatan, penyimpanan, pendokumentasian, hingga verifikasi surat, semua dilakukan secara konvensional. Dokumentasi surat masuk dan keluar hanya berupa penulisan di buku besar. Sedangkan pada tahap pengarsipan surat hanya berupa penyimpanan dokumen hardcopy. Dengan adanya masalah yang telah sebutkan, Badan Pelayanan Perizinan Terpadu (BPPT) Kabupaten Karanganyar dirasa perlu untuk merubah metode manajemen persuratan yang saat ini mereka gunakan, yaitu metode konvensional, menjadi metode manajemen persuratan yang terkomputerisasi dan otomatis. Dengan adanya Sistem Informasi Manajemen Agenda, diharapkan menghasilkan aplikasi yang dapat mengelola surat masuk dan keluar sesuai alur yang di tetapkan, dan dapat menyelesaikan masalah yang ada saat ini. Penelitian ini dilakukan untuk membuat aplikasi berbasis web, yang dapat mengelola surat masuk dan keluar secara efektif sesuai alur yang telah ditetapkan oleh Badan Pelayanan Perizinan Terpadu (BPPT) Kabupaten Karanganyar. Adapun metode penelitian yang guna untuk menyelesaikan berbagai permasalahan yang terjadi adalah pustaka, observasi, wawancara, analisis data dan system, perancangan system, pembuatan program, pengujian program, implementasi program.  Kata Kunci : Sistem Informasi Manajemen Agenda  

 		Apotek “Jati Farma” merupakan satu-satunya toko obat yang ada di Kecamatan Arjosari. Tepatnya di pinggir jalan raya Pacitan-Ponorogo Km.10, dan berdekatan dengan pasar Arjosari. Dengan lokasinya yang sangat strategis tersebut, memudahkan para warga untuk menjangkau tempatnya. Dengan kemajuan teknologi yang semakin canggih, sekarang ini masih banyak sekali bahkan hampir semua toko obat (apotek) yang guna cara konvensional untuk mengerjakan tugas-tugas yang berkaitan dengan apotek. Salah satunya adalah Apotek Jati Farma di Kecamatan Arjosari. Apotek ini memiliki permasalahan pada pencatatan transaksi yang bersifat konvensional. Karena itu dibutuhkan sebuah sistem yang dapat atas hal tersebut. Software yang guna untuk pembuatan sistem ini adalah Visual Basic 6.0, Mysql connector odbc, xampp sebagai servernya dan MySql untuk databasenya. Tujuan dari penelitian ini adalah untuk membuat sistem pencatatan obat (pembelian-penjualan) yang bersifat komputerisasi. Manfaatnya adalah agar memudahkan proses pencatatan data obat, baik itu pembelian ataupun penjualan. Metode yang guna adalah kepustakaan, observasi, wawancara dan analisis. Dari pembuatan sistem ini, harapannya bisa meringankan tugas asisten apoteker dan membuat kinerja apotek menjadi lebih efektif dan efisien. Kata kunci : Sistem Informasi, Sistem Informasi Apotek 


		Program Nasional Pemberdayaan Masyarakat Mandiri Pedesaan  (PNPM-MPd) adalah program untuk mempercepat penanggulangan kemiskinan secara terpadu dan berkelanjutan. Salah satu kegiatan yang diselenggarakan PNPM Mandiri adalah  kegiatan SPP (Simpan Pinjam khusus Perempuan). Seperti simpan pinjam yang dikelola oleh Unit Pengelola Kegiatan (UPK) Mitra Usaha Mandiri di Kecamatan Pringkuku Kabupaten Pacitan. Dalam pengelolaannya, SPP ini masih guna alat bantu konvensional yaitu masih guna buku besar.  Penelitian ini dilakukan untuk membuat dan menghasilkan perangkat lunak untuk pengolahan data  simpan pinjam yang dapat menghemat dan mempercepat  waktu input dan output data yang sebelumnya masih guna sistem konvensional. Adapun metode penelitian yang guna untuk menyelesaikan berbagai permasalahan yang terjadi adalah pustaka, observasi, wawancara, analisis data dan sistem, perancangan sistem, pembuatan program, pengujian program, implementsi program. Yang dihasilkan dari penelitian ini adalah sebuah sistem yang dapat  memudahkan admin dalam pencarian data, menghemat waktu dalam input data,output data didapat secara cepat, tepat dan akurat, data dapat dikontrol dengan baik serta mengurangi tingkat kesalahan data. Kata Kunci : Sistem Pengolahan Data Simpan Pinjam   
	}

$multimedia = array();
	foreach ($variable as $key => $value) 
	{
		
		Proses pembelajaran tidak akan mencapai hasil yang optimal jika tidak diimbangi oleh keragaman pendekatan dan metode, baik pendekatan individual, kelompok, maupun klasikal. Perangkat Computer Based Learning (CBL) dikembangkan dengan tujuan untuk membantu siswa dalam memahami konsep-konsep materi pembelajaran yang disajikan secara interaktif oleh sistem serta mampu memberikan informasi lebih baik. Masalah yang dibahas dan diteliti adalah bagaimana merancang aplikasi mulitimedia pembelajaran sebagai alternatif media pembelajaran yang efektif. Meteri yang digunakan terdiri dari gabungan teks, grafik, audio, animasi dan video. Penelitian dilakukan di SMA 5 Pekanbaru dan bertujuan untuk menghasilkan aplikasi multimedia interaktif yang efektif. Apliksi yang dihasilkan dapat menjadi pilihan untuk menyampaikan materi pembelajaran serta untuk menimbulkan minat belajar serta kepahaman siswa terhadap materi pelajaran sehingga dapat meningkatkan prestasi belajar siswa.


		Makalah ini membahas tentang pembuatan aplikasi film animasi 2D dengan tema sedekah  menggunakan teknik 2D Hybrid Animation dengan pemanfaatan Graphic yang mengandung nilai edutaiment untuk anak-anak. Edutainment dapat digunakan oleh guru maupun orang tua untuk memberikan pelajaran atau mengubah perilaku dan karakter pada anak seperti karakter suka bersedekah. Film animasi memiliki fungsi sebagai alat penghibur dan sebagai media pembelajaran untuk anak sehingga anak tidak merasa bosan dan membuat belajar menjadi menyenangkan karena adanya unsur hiburan. Namun, beberapa animasi populer mempromosikan perilaku negatif seperti adegan kekerasan dalam bentuk fisik (perkelahian) atau kekerasan non fisik. Dari sekian banyak film animasi yang ditayangkan ditelevisi, belum banyak film yang mengajarkan tentang sesuatu yang mengandung makna islam, misalnya tentang sedekah. Kebanyakan film animasi merupakan film buatan luar negeri dan hanya menceritakan tentang petualangan, perang, perselisihan, imajinasi, dan lain-lain. Film animasi ini diuji cobakan kepada orang tua, guru, dan anak-anak PAUD maupun TK. Hasil uji coba menunjukkan bahwa film animasi ini menarik jalan ceritanya dan layak untuk ditonton oleh anak usia 2-8 tahun dan mengandung nilai edutaiment baik secara moral maupun religious serta dapat menghibur anak-anak. Anak-anak sangat antusias dalam menonton film animasi ini dan meminta untuk memutar kembali film animasi secara berulang-ulang. Anak-anak ingin selalu membantu orang yang mengalami kesulitan yaitu dengan cara menyisihkan uang jajannya untuk bersedekah agar dapat membantu meringankan beban penderitaan orang lain serta mendapat pahala dari Allah AWT.   Kata kunci : film animasi 2D, 2D Hybrid Animation, Graphic, Edutaiment.

		Aplikasi pembelajaran pengenalan bentuk untuk anak ini adalah suatu aplikasi pembelajaran pengenalan bentuk pada anak pra TK dengan bantuan komputer. Aplikasi ini merupakan suatu media pembelajaran mengenal bentuk yang terdiri dari bagian tutorial dalam bentuk permainan serta bagian evaluasi. Didalam membuat suatu Aplikasi pembelajaran yang berbasis multimedia ini, diperlukan suatu program yang mampu mengkombinasikan teks, grafik, suara dan animasi. Informasi dalam bentuk multimedia juga lebih menarik dan interaktif dibandingkan dengan informasi dalam bentuk teks. Untuk mewujudkan hal tersebut digunakan perangkat lunak Macromedia Flash MX untuk membuat perangkat lunak ini. Pengujian sistem dengan black box test dan alfa test. Hasil uji coba sistem menujukkan bahwa aplikasi ini menarik minat anak belajar bentuk dengan permainan menggunakan multimedia yang interaktif, gambar dengan suara sehingga tidak membosankan, serta game yang dapat mengalihkan kejenuhan saat belajar.  Keywords  Pembelajaran, Bentuk, Game, Macromedia Flash MX


		 Saat ini untuk mempelajari hewan purbakala melalui pelajaran sejarah di sekolah hanya dilakukan hanya melalui sebuah buku dan gambar yang terdapat pada buku-buku dan alat peraga biasa, tetapi dengan menggunakan teknologi augmented reality diharapkan dalam pembelajarannya dapat membuat pelajaran sejarah terutama mengenai hewan purbakala dapat lebih menarik dan menyenangkan karena augmented reality dapat menjadi sebuah alat peraga virtualisasi hewan purbakala dlam bentuk 3D. Aplikasi augmented reality ini sebagai media pengenalan hewan purbakala kepada anak-anak usia 13 sampai 18 tahun secara virtual menggunakan perangkat smartphone agar proses pengenalan Hewan purbakala dapat menjadi lebih menarik dan mudah diapliaksikan karena mudah dibawa serta tidak menggunakan alat peraga yang sulit didapat dan memiliki harga yang mahal. Virtualisasi Alat Peraga Pengenalan Hewan Purbakala menggunakan augmented reality dapat menampilkan Animasi Hewan purbakala dalam bentuk 3D. Dengan proses, pengguna menjalankan aplikasi kemudian aplikasi akan melakukan pelacakan marker, setelah marker dikenali sesuai data acuan yang terdapat didalam sistem aplikasi, maka aplikasi dapat menampilkan binatang Purbakala secara 3D pada layar smartphone. 
		Kata kunci – Augmented Reality, Virtualisasi, Hewan Purbakala, Smartphone. 


		Makalah ini menyajikan teknik yang bisa digunakan untuk menghasilkan foto atau gambar yang menyerupai lukisan (painterly rendering). Teknik ini memanfaatkan serangkaian sikat yang memiliki berbagai ukuran, panjang, dan warna. Varian dari sikat ini kemudian digunakan sebagai parameter. Parameter menentukan jenis lukisan yang akan terbentuk. Tulisan ini membahas teknik penyajian beberapa pelukis gaya dengan menggunakan brush B-Spline. Kata kunci: Rendering Non-Photorealistic, Rendering Praktis, Rendering berbasiskan stroke


		Pada permainan Game Kamen Rider Decade ini sangat membutuhkan strategi yang tepat jika ingin memenangkan dengan mudah permainan ini. Penelitian ini bertujuan untuk mengimplementasikan metode Dept First Search (DFS) dan Breadth First Search (BFS) pada Game Kamen Rider Decade, yang merupakan permainan dengan strategi penyelesaiannya menggunakan metode pencarian buta (blind search). Pengumpulan data dilakukan dengan pendekatan kualitatif dengan metode deskriptif, dimana pengujian dilakukan dengan memainkan 3 kali masing-masing dengan metode selalu BFS dan selalu DFS. Hasil menunjukan peluang lebih besar memenangkan permainan ini adalah dengan strategi selalu BFS. Dimana kemampuan BFS pada permainan ini dapat berguna untuk pertahanan terhadap musuh.  
		Kata Kunci: Game Kamen Rider Decade, BFS, DFS, Strategi   


		Game merupakan media hiburan dengan
		pertumbuhan paling tinggi di antara media audio visual
		lainnya seperti musik, tv, dan film. Game hanya kalah dari
		pertumbuhan internet yang juga sangat luar biasa
		perkembangannya Game selain memiliki potensi yang
		amat besar dibidang Ekonomi, game bukan hanya sebagai
		media hiburan tetapi lebih kompleks lagi, Salah satu
		diantaranya fungsi komunikasi.
		Indonesia hingga saat ini tidak memiliki data
		lengkap mengenai seni budaya yang tersebar di setiap
		daerah. Perlindungan hak cipta terhadap seni budaya juga
		sangat lemah, sedangkan publikasi multimedia secara
		internasional mengenai produk seni budaya masih sangat
		minim. Akibat berbagai kelemahan ini, seni budaya
		Indonesia sering diklaim negara lain.
		Dengan memanfaatkan fungsi game sebagai media
		massa maka merancang sebuat game dengan cerita,
		concept art karakter dan environment yang memuat
		informasi budaya Indonesia diharapkan dapat menjadi
		publikasi multi media yang dibutuhkan oleh budaya
		Indonesia untuk melindungi dari klaim pihak asing.


		Penelitian ini mengambil judul ”Pembuatan Film Animasi 2D Yang Berjudul Empat Monster Pada Komunitas Multimedia Amikom Surakarta“  dengan tujuan untuk memberikan hiburan, inspirasi, dan juga sebagai menyampaikan pesan moral pada khalayak umum. Metode yang digunakan dalam penelitian ini adalah metode pengembangan multimedia. Metode pengumpulan datanya menggunakan metode observasi, wawancara, dan studi pustaka. Hasil penelitian ini berupa film animasi 2 dimensi yang mampu menghibur dan menyampaikan pesan moral kepada masyarakat.  Kata Kunci : Animasi 2 Dimensi, Empat Monster, Film Animasi, Komunitas Multimedia Amikom Surakarta   


		Kata kunci: Multimedia, Animasi 3D, Animasi Pertarungan teknologi informasi berkembang sangat pesat, termasuk perkembangan dunia animasi. Saat ini banyak muncul berbagai macam film Animasi 3D dengan beragam cerita, dan adegan aksi seru seperti animasi berkelahi. Proses pembuatan film animasi 3D memang membutuhkan persiapan dan kuat untuk menghasilkan animasi 3D yang bagus dan menarik. Dalam tulisan ini penulis mencoba membuat animasi 3D berbentuk cerita fiksi yang menceritakan tentang sebuah planet yang memiliki banyak balapan. Planet ini adalah pejuang yang tangguh. Pada suatu waktu, planet yang berkuasa mengadakan sebuah kontes untuk memenangkan pertarungan dan akan mendapatkan pedang. Pedang adalah pedang bernama Khamp. Proses pembuatan animasi 3D Khamp memang membutuhkan persiapan untuk menghasilkan animasi 3D yang menarik. Program yang digunakan adalah Autodesk Maya 2012 untuk membuat karakter dan tempat, Autodesk Montion Builder 2013 untuk memindahkan karakter, Adobe Photoshop untuk pembuatan tekstur, Adobe Audition untuk audio, dan Adobe Premiere Pro CS3 untuk mengedit hasil animasi dan audio.


		Penelitian ini adalah untuk membuat Pembuatan film pendek action format 3D yang berjudul War Of Machine menggunakan Autodesk 3Ds Max. Tujuan khusus dari penelitian ini adalah untuk mengetahui bagaimana menerangkan secara besar tata cara pembuatan film dengan spesifikasi rumahan. Di dalam Pembuatan film pendek action format 3D yang berjudul War Of Machine menggunakan Autodesk 3Ds Max teknik yang digunakan adalah teknik rigging character. Hasil dan analisa diselenggarakan adalah menunjukkan bahwa pembuatan film dengan teknik yang sederhana dan basic didalam editing video ternyata sangat mudah dan user friendly. Kata kunci: Pembuatan film pendek action format 3D yang berjudul War Of Machine menggunakan Autodesk 3Ds Max 


	}

$Network = array();
	foreach ($variable as $key => $value) 
	{
				Dalam dunia bisnis, biasanya sebuah organisasi ingin membangun Wide Area Network (WAN) untuk menghubungkan beberapa kantor cabangnya. Sebelum munculnya Virtual Private Network (VPN), mereka umumnya menggunakan ” leased line” yang mahal sehingga hanya perusahaan besar yang dapat memilikinya.
		VPN - WAN memberi solusi alternatif karena dapat mengurangi biaya pembuatan infrastruktur jaringan dan memotong biaya operasional dengan memanfaatkan failitas internet sebagai media komunikasinya. Perusahaan cukup menghubungi  Internet Service Provider (ISP) terdekat untuk mendapatkan layanan ini.Setiap paket informasi yang dikirim dapat diakses, diawasi atau bahkan dimanipulasi oleh pengguna. Supaya komunikasi berjalan aman maka diperlukan protokol tambahan khusus yang dirancang untuk mengamankan data yang dikirim.  Dewasa ini sudah banyak perusahaan seperti : perusahaan manufaktur, distribusi dan retail; pertambangan minyak dan gas, telekomunikasi, finansial, pemerintahan serta industri transportasi yang menggunakan VPN karena fasilitas –fasilitas yang ditawarkan berupa remote access client, internetworking LAN to LAN serta akses yang terkontrol dengan biaya yang murah.  Uji coba yang dilakukan Miercom(LAB penyedia testing kinerja perangkat keras) terhadap  Cisco 1841 membuktikan bahwa Cisco 1841 dapat  menopang suatu komunikasi dua arah, interkoneksi IP WAN kapasitas E1 dengan enkripsi 3DES yang dapat menunjang throughput sampai dengan 2 Mbps dalam koneksi E1 IP-WAN.
		 Penggunaan  VPN akan meningkatkan efektivitas, efisiensi kerja serta skalabilitas perusahaan. Keuntungan lain yang didapat dari VPN adalah pada biaya pulsa yang jauh lebih murah dibandingkan dengan menggunakan” leased line”.

		  Penelitian ini dilakukan dengan skenario uji kelayakan berdasarkan kebutuhan user. Pengujian-pengujian yang dilakukan adalah Pengujian Konektivitas, Pengujian Transfer Data, Attacking VPN dengan DoS (Denial Of Services), Hacking VPN dengan ARP Poisoning di Linux Backtrack. Hasil eksperimen pengujian attacking dengan Denial of Service (DoS) menggunakan tool pingflood ternyata berhasil mematikan service/layanan pada VPN server. Selain itu pengujian hacking / ARP Poisoning untuk mendapatkan username dan password dengan menggunakan tools yang ada pada Linux backtrack juga berhasil menembus akses login client ke server. 

		  Jaringan wireless LAN adalah jaringan yang mengkoneksikan dua komputer atau lebih menggunakan sinyal radio, cocok untuk berbagi-pakai file, printer, atau akses internet. Dengan mempergunakan perangkat radio maka akan dapat membuat LAN tanpa menggunakan kabel data yang umum dipakai dalam sebuah jaringan komputer. Setiap PC pada jaringan wireless dilengkapi dengan sebuah radio tranceiver atau biasanya disebut adapter atau kartu Wireless LAN yang akan mengirim dan menerima sinyal radio dari dan ke PC lain dalam jaringan. Teknologi wireless memungkinkan jaringan ini dapat dipasang di tempat dimanajaringan kabel tidak dapat dipasang.  Laboratorium komputer yang digunakan untuk pembelajaran pelajaran produktif teknik komputer jaringan masih kurang memadai. Yang sering terjadi adalah tabrakan jam praktik dengan yang lain, siswa sering bosan dan jenuh dengan pelajaran yang monoton, dan juga belum adanya media pembelajaran yang interaktif di Sekolah Menengah Kejuruan Taruna Bangsa Pati membuat pembelajaran kurang maksimal. Dengan penelitian ini diharapkan siswa bisa memahami materi pelajaran produktif teknik komputer jaringan, mengurangi kebosanan dan kejenuhan siswa, dan minat belajar siswa akan lebih bertambah.  Kata kunci/Key word :  Media pembelajaran, Komputer Jaringan

		  Network storage dibangun di atas platform OpenFiler yang memiliki berbagai keunggulan, yaitu dapat menyatukan konsep media penyimpanan NAS dan SAN dalam sebuah mesin, manajemen data menggunakan quota, serta kompatibilitasnya jika digunakan sebagai media penyimpanan dengan berbagai sistem autentikasi. Network storage dapat secara otomatis termapping sebagai sebuah drive pada komputer client dengan bergabung ke dalam domain yang ditangani oleh sebuah domain controller menggunakan Samba.Proses autentikasi pengguna sistem dibangun di atas platform OpenLDAPsehingga selanjutnya dapat dipergunakan untuk validasi pengguna pada berbagai sistem yang mendukung interkoneksi dengan OpenLDAP seperti FreeRadius yang akan digunakan untuk mendukung validasi pengguna layanan koneksi internet pada internet gateway. 

		   perlu untuk adanya sistem yang berguna untuk backup file. Network Attached Storage (NAS) adalah sebuah server dengan sistem operasi yang dikhususkan untuk melayani kebutuhan berkas data. NAS dapat berbentuk perangkat yang siap pakai atau berupa sebuah software yang akan di-install-kan pada sebuah komputer agar berubah fungsi menjadi server NAS. Untuk software ini menggunakan NAS4Free yang berbasis linux. Model pengembangan sistem menggunakan Network Development Life Cycle (NDLC), adapun siklus tahapannya berisi analysis, design, simulation, prototyping, implementation, monitoring sehingga perencanaan yang akan dilakukan diharapkan bisa maksimal. Berdasarkan hasil pengujian terhadap rata-rata upload-nya adalah 3,5 Mbps, sedangkan untuk rata-rata  download-nya adalah 5,63Mbps. 

		   Virtual server adalah server yang mempunyai skalabilitas dan ketersedian yang tinggi yang dibangun diatas sebuah  cluster dari beberapa  real server.  Real server dan  load balancer akan saling terkoneksi baik dalam jaringan lokal kecepatan tinggi atau yang terpisah secara geografis. Load balancer dapat mengirim permintaan-permintaan ke  server yang berbeda dan membuat paralel service dari sebuah cluster pada sebuah alamat IP tunggal dan meminta pengiriman dapat menggunakan teknologi IP  load balancing atau level aplikasi teknologi  load balancing. Linux  Virtual Serverjuga mampu memeratakan beban  request / paket dari client kepada beberapa Real-Server yang telah ter-clusterdan terintegrasi pada sebuah Virtual-Service.

		   Tujuan penulisan ini adalah untuk dapat mengetahui kinerja perancangan jaringan komputer Universitas Teknologi Sumbawa yang telah dibangun di simulator OPNET Version 14.5, dari mana disain jaringan komputer terdiri dari dua desain khusus desain jaringan komputer. menggunakan Media Kabel dan Media Nirkabel (Access Point). Penelitian dimulai dengan menganalisis situasi saat ini dari jaringan komputer dan menemukan keadaan pemanfaatan jaringan komputer yang belum optimal karena kondisi infrastruktur jaringan komputer rektor Universitas Teknologi Sumbawa hanya ditemukan di bangunan utama itu sendiri. Proses analisis dan perancangan infrastruktur jaringan komputer menggunakan Network Development Life Cycle (NDLC). Hasil perbandingan desain dengan Media Kabel di Simulator memiliki Page Response Time 82,3% lebih cepat daripada menggunakan Wireless Media dan delay point Cable Media yang 19,1% lebih rendah dari Wireless Media. Oleh karena itu Cable Media dapat dianggap sebagai salah satu pilihan Dewan Eksekutif Universitas Teknologi Sumbawa untuk mengembangkan Infrastruktur Jaringan Komputer untuk mengintegrasikan keseluruhan bangunan yang ada di dalam area kampus untuk mendukung implementasi sistem informasi.
			Kata kunci: Jaringan Komputer, Kabel, Nirkabel, OPNET

			Penelitian ini mengambil judul ”Pembuatan Film Animasi 2D Yang Berjudul Empat Monster Pada Komunitas Multimedia Amikom Surakarta“  dengan tujuan untuk memberikan hiburan, inspirasi, dan juga sebagai menyampaikan pesan moral pada khalayak umum. Metode yang digunakan dalam penelitian ini adalah metode pengembangan multimedia. Metode pengumpulan datanya menggunakan metode observasi, wawancara, dan studi pustaka. Hasil penelitian ini berupa film animasi 2 dimensi yang mampu menghibur dan menyampaikan pesan moral kepada masyarakat.  Kata Kunci : Animasi 2 Dimensi, Empat Monster, Film Animasi, Komunitas Multimedia Amikom Surakarta   

			teknologi informasi berkembang sangat pesat, termasuk perkembangan dunia animasi. Saat ini banyak muncul berbagai macam film Animasi 3D dengan beragam cerita, dan adegan aksi seru seperti animasi berkelahi. Proses pembuatan film animasi 3D memang membutuhkan persiapan dan kuat untuk menghasilkan animasi 3D yang bagus dan menarik. Dalam tulisan ini penulis mencoba membuat animasi 3D berbentuk cerita fiksi yang menceritakan tentang sebuah planet yang memiliki banyak balapan. Planet ini adalah pejuang yang tangguh. Pada suatu waktu, planet yang berkuasa mengadakan sebuah kontes untuk memenangkan pertarungan dan akan mendapatkan pedang. Pedang adalah pedang bernama Khamp. Proses pembuatan animasi 3D "Khamp" memang membutuhkan persiapan untuk menghasilkan animasi 3D yang menarik. Program yang digunakan adalah Autodesk Maya 2012 untuk membuat karakter dan tempat, Autodesk Montion Builder 2013 untuk memindahkan karakter, Adobe Photoshop untuk pembuatan tekstur, Adobe Audition untuk audio, dan Adobe Premiere Pro CS3 untuk mengedit hasil animasi dan audio. Kata kunci: Multimedia, Animasi 3D, Animasi Pertarungan

			Penelitian ini adalah untuk membuat Pembuatan film pendek action format 3D yang berjudul War Of Machine menggunakan Autodesk 3Ds Max. Tujuan khusus dari penelitian ini adalah untuk mengetahui bagaimana menerangkan secara besar tata cara pembuatan film dengan spesifikasi rumahan. Di dalam Pembuatan film pendek action format 3D yang berjudul War Of Machine menggunakan Autodesk 3Ds Max teknik yang digunakan adalah teknik rigging character. Hasil dan analisa diselenggarakan adalah menunjukkan bahwa pembuatan film dengan teknik yang sederhana dan basic didalam editing video ternyata sangat mudah dan user friendly. Kata kunci: Pembuatan film pendek action format 3D yang berjudul War Of Machine menggunakan Autodesk 3Ds Max 

	}

$database = array();
	foreach ($variable as $key => $value) 
	{
		Network storage dibangun di atas platform OpenFiler yang memiliki berbagai keunggulan, yaitu dapat menyatukan konsep media penyimpanan NAS dan SAN dalam sebuah mesin, manajemen data menggunakan quota, serta kompatibilitasnya jika digunakan sebagai media penyimpanan dengan berbagai sistem autentikasi. Network storage dapat secara otomatis termapping sebagai sebuah drive pada komputer client dengan bergabung ke dalam domain yang ditangani oleh sebuah domain controller menggunakan Samba.Proses autentikasi pengguna sistem dibangun di atas platform OpenLDAPsehingga selanjutnya dapat dipergunakan untuk validasi pengguna pada berbagai sistem yang mendukung interkoneksi dengan OpenLDAP seperti FreeRadius yang akan digunakan untuk mendukung validasi pengguna layanan koneksi internet pada internet gateway. 	 perlu untuk adanya sistem yang berguna untuk backup file. Network Attached Storage (NAS) adalah sebuah server dengan sistem operasi yang dikhususkan untuk melayani kebutuhan berkas data. NAS dapat berbentuk perangkat yang siap pakai atau berupa sebuah software yang akan di-install-kan pada sebuah komputer agar berubah fungsi menjadi server NAS. Untuk software ini menggunakan NAS4Free yang berbasis linux. Model pengembangan sistem menggunakan Network Development Life Cycle (NDLC), adapun siklus tahapannya berisi analysis, design, simulation, prototyping, implementation, monitoring sehingga perencanaan yang akan dilakukan diharapkan bisa maksimal. Berdasarkan hasil pengujian terhadap rata-rata upload-nya adalah 3,5 Mbps, sedangkan untuk rata-rata  download-nya adalah 5,63Mbps. 	" Saat ini, aplikasi data komputer adalah sebuah kemampuan dan kinerja yang semakin meningkat dari sistem basis data. Meningkatnya jumlah data yang disertai dengan pengolahan secara terpusat akan berujung tidak optimal.  Ketidak optimalan tersebut berupa nilai response time yang tinggi. Hal tersebut bertentangan dengan salah satu tujuan pemrosesan pada basis data yakni nilai response time yang minim. Untuk mengatasi permasalahan tersebut diperlukan sebuah arsitektur basis data selain basis data terpusat. Teknologi basis data terdistribusi mempunyai pengertian bahwa semua komputer saling terhubung dan setiap sistem mempunyai hak kemampuan memproses untuk melayani permintaan lokal. Setiap sistem berpartisipasi baik dalam melaksanakan satu atau lebih permintaan. Setiap site dalam lingkungan replikasi multimaster adalah site utama, dan masing-masing site utama berkomunikasi dengan site utama lainnya. Sistem database terdistribusi menggunakan beberapa komputer yang terhubung dan bekerja secara lokal sehingga membentuk satu kesatuan kerja   
		Kata kunci: basis data terdistribusi, replikasi multimaster  "	" Analisis proses belajar mengajar dalam suatu universitas merupakan salah satu alat bantu yang digunakan untuk mengambil keputusan dalam proses belajar mengajar berikutnya maupun untuk permasalahan-permasalahan yang terjadi pada proses belajar mengajar tersebut. Data warehouse dapat membantu penyediaan data yang dibutuhkan dalam pengukuran kinerja proses belajar mengajar tersebut. Informasi yang dihasilkan pada data warehouse tersebut adalah kinerja dosen, kinerja mahasiswa, tingkat kelulusan mata kuliah dan summary dari nilai tiap mata kuliah.
		Kata kunci: data warehouse, pengukuran kinerja proses belajar mengajar
		"	"Indonesia merupakan daerah rawan multi bencana alam, yang sering terjadi tanpa dapat diprediksikan terlebih dahulu. Bencana alam tersebut telah berdampak pada timbulnya korban jiwa, kerusakan lingkungan, kerugian harta benda, dan dampak psikologis sehingga dalam keadaan tertentu dapat menghambat pembangunan nasional. Kebutuhan data dan informasi geospasial (IG) terkait kebencanaan ini, sangat penting dalam penanganan bencana. Sebagai institusi yang berwenang dan bertanggung jawab terhadap penyelenggaraan IG dasar dan pembinaan IG tematik nasional, Badan Informasi Geospasial (BIG) perlu menyediakan layanan data terkait kebencanaan, yang melibatkan berbagai data dan informasi geospasial tematik. Dalam penyediaan layanan tersebut, BIG membangun sebuah Geospatial Support Command Center (GSCC), yang diperlukan untuk menyediakan layanan data dan IG terintegrasi dalam suatu data warehouse.  Penelitian ini dilakukan untuk memberikan rekomendasi desain dan pengintegrasian data melalui perancangan dan pengimplementasian data warehouse spasial di BIG yang dapat mendukung layanan IG untuk kebencanaan. Pendekatan data warehouse spasial yang digunakan adalah pendekatan analysis-driven yang dikemukakan oleh Malinowski dan Zimanyi.  Hasil akhir dari penelitian ini adalah implementasi data warehouse spasial serta dashboard spasial, sehingga dapat mempermudah pemanfaatan informasi terkait bencana. Hasil penelitian ini memberikan rekomendasi berupa lokasi kejadian, sehingga penanganan bencana dapat tepat dan sesuai sasaran.   data tingkat lanjut. 
		Kata kunci : Sistem basis data, pengelolaan data, profil siswa, visual studio, program aplikasi
		"	"Analisis sistem penyimpanan data di Cloud Computing dengan studi kasus SMK N 2 Karanganyar untuk membandingkan efisiensi menggunakan cloud computing. Hal ini disebabkan karena penyimpanan data yang ada di SMK N 2 karanganyar masih menggunakan komputer server.  Tanggung jawab apabila menggunakan server harus memiliki hardware yang tepat dan perangkat lunak yang dibutuhkan untuk melakukan pekerjaan. Membeli komputer untuk setiap orang tidak akan cukup, belum lagi harus membeli lisensi perangkat lunak dan alat untuk karyawan yang dibutuhkan. Dengan memiliki seorang karyawan baru harus membeli perangkat lunak yang lebih lisensi perangkat lunak yang memungkinkan bagi pengguna lain. Hal ini membuat merasa sulit untuk penggunaan server. Dalam sistem cloud computing, ada pergeseran beban kerja yang signifikan.  Komputer lokal tidak lagi harus melakukan semua beban berat ketika digunakan. Jaringan komputer yang cloud ini menangani mereka sebagai gantinya. Hardware dan software pada sisi pengguna menurun. Satu-satunya hal dimana komputer pengguna harus mampu untuk menjalankan adalah antarmuka perangkat lunak sistem cloud computing, yang sederhana sebagai peramban Web, dan cloud network akan mengurus sisanya.  Oleh sebab itu cloud computing sangat diperlukan demi mengefisien waktu.

		Kata Kunci : Cloud Computing,"	Proses migrasi data biasanya dibutuhkan saat adanya perubahan sistem, format, atau tipe storage. Saat ini telah dikenal beberapa teknik dan kakas untuk melakukan migrasi data, misalnya CSV file, ODBC, SQLDump dan sebagainya. Sayangnya tidak semua teknik tersebut dapat diimplementasikan untuk migrasi data antara dua DBMS yang berbeda. Dalam penelitian ini dipaparkan sebuah teknik migrasi data yang dapat digunakan untuk migrasi data lintas DBMS. Teknik migrasi data yang dipaparkan memanfaatkan metadata yang ada di masing-masing DBMS. Proses migrasi data yang dipaparkan di sini melalui tiga tahap yaitu capture, convert dan construct. Sebuah prototype dibangun untuk menguji teknik migrasi data ini. Dengan menggunakan schema HR dilakukan uji coba migrasi data lintas DBMS antara Oracle dan MySQL. Dengan menggunakan teknik ini, migrasi data full-schema membutuhkan waktu rata-rata 20,43 detik dari DBMS Oracle ke MySQL dan 12,96 detik untuk skenario sebaliknya. Adapun untuk migrasi data parsial dibutuhkan waktu rata-rata 5,95 detik dari DBMS Oracle ke MySQL dan 2,19 detik untuk skenario sebaliknya.	"Penelitian ini bertujuan untuk mengetahui (1) penerapan sistem informasi akuntansi (SIA) berbasis komputer dengan pendekatan database management system (DBMS) pada Koperasi Simpan Pinjam (KSP) Asri Sari Utama Mandiri, dan (2) efektivitas penerapan SIA berbasis komputer dengan pendekatan DBMS pada KSP Asri Sari Utama Mandiri. Data dikumpulkan dengan metode wawancara, kuisioner dan dokumentasi, yang selanjutnya dianalisis dengan analisis deskriptif kuantitatif. Hasil penelitian menunjukkan bahwa (1) penerapan penerapan SIA berbasis komputer dengan pendekatan DBMS pada KSP Asri Sari Utama Mandiri terdiri dari tiga proses yaitu input, proses pada DBMS, dan output dan (2) efektivitas penerapan SIA berbasis komputer dengan pendekatan DBMS pada KSP Asri Sari Utama Mandiri yang diukur melalui enam indikator yaitu independensi data, standarisasi data, integrasi data, waktu, keamanan data dan variasi laporan berada pada kriteria efektif. Hal ini dapat dilihat dari perolehan masing-masing indikator, yaitu berdasarkan indikator independensi data dengan kriteria efektif (288), indikator standarisasi data dengan kriteria efektif (249), indikator integrasi data dengan kriteria efektif (314), indikator waktu dengan kriteria efektif (312), indikator keamanan data dengan kriteria efektif (260), dan indikator variasi laporan dengan kriteria sangat efektif (266).
		Kata kunci: DBMS, efektivitas, dan SIA"	"Besarnya data pelaporan EPSBED dari Prodi ke PDPT-Universitas hingga ke PDPT-DIKTI membutuhkan sarana integrasi dan komunikasi data yang konsisten, belum mengikuti standarisasi pengelolaan database terpusat pada siklus manajemen yang terkait dengan sistem Pangkalan Data Pendidikan Tinggi (PDPT). Penelitian ini bertujuan membangun sistem informasi yang memiliki  integritas, konsistensi dan validitas data antar Program Studi dan PDPT Universitas. Metode yang digunakan meliputi studi lapangan dan kepustakaan untuk mengetahui data pelaporan EPSBED dari Prodi ke PDPT-Universitas hingga ke PDPT-DIKTI, perancangan sistem informasi dan basis data menggunakan Convention Over Configuration, pemodelan sistem Unified Modeling Language, pengelolaan Data Base Management System menggunakan PostgreSQL, dan port TCP-IP sebagai sarana komunikasi data. Hasil penelitian ini menunjukkan penerapan sistem replikasi yang bersifat real time sebagai  bentuk alternatif pengiriman data berjumlah besar, menjamin sinkronisasi integrasi basis data dari server asal ke server tujuan, dan sistem replikasi DBMS menggunakan PostgreSQL membantu DBMS Program Studi terintegrasi dan terkorelasi langsung dengan PDPT-Universitas.  
		Kata kunci: PDPT, Replikasi, Basis data , PostgreSQL.  "	"Migrasi Data adalah proses pemindahan data antara dua jenis database yang 
		berbeda format maupun pengolahan data saat melakukan suatu perpindahan sistem 
		seperti uprade hardware,software maupun sistem. Database yang sering digunakan 
		oleh user salah satunya adalah MySQL dan SQL Server. Proses migrasi data terdapat 
		beberapa proses diantaranya pemindahan data dari satu DBMS ke DBMS lainnya, 
		pengaksesan struktur skema maupun tabel dan setelah proses migrasi berhasil 
		terdapat notifikasi migrasi berasil dan akan tersimpan dalam histori agar dapat 
		melihat kembali kegiatan yang sudah pernah dilakukan dalam proses migrasi 
		data.Proses migrasi data pada kenyataannya masih menggunakan bantuan beberapa 
		tools dan sintaks tertentu dimana hasil migrasi tidak tersimpan.Dalam 
		pengaplikasiannya, tidak banyak orang yang memahami sintaks maupun tools untuk 
		proses migrasi data sehingga untuk melakukan proses migrasi data cukup terhambat 
		serta pemahaman dan support tools yang memadai dalam melakukan migrasi data.  
		Proyek akhir ini bertujuan memberikan salah satu alternatif yang dapat membantu 
		memenuhi maupun menanggani semua kebutuhan dan user friendly, sehingga dapat 
		membantu siapapun yang akan melakukan proses migrasi data tanpa harus 
		memahami sintaks,tools ataupun lainnya.  
		Kata Kunci: Migrasi Data, MySQL, SQL Server, ODBC Driver "

	}

$sistem_kemanan = array();
	foreach ($variable as $key => $value) 
	{
		Identifikasi wajah merupakan sebuah proses face detection yang mudah untuk diimplementasikan di dalam bidang penelitian pemrosesan wajah (face processing), pendeteksian wajah manusia merupakan suatu tahap awal yang sangat penting di dalam proses pengenalan wajah (face recognition). Sistem pengenalan wajah digunakan untuk membandingkan satu citra wajah inputan dengan suatu database wajah dan menghasilkan wajah yang paling cocok dengan citra tersebut jika terdeteksi.Sedangkan autentikasi wajah (face authentication) digunakan untuk menguji keaslian/kesamaan suatu wajah dengan data wajah yang telah tersimpan di dalam database sebelumnya. Aplikasi memiliki keunggulan dibanding dengan metode konvensional Dalam hal tidak mudah dicuri atau digunakan oleh pengguna yang tidak berwenang.  Sistem pengenalan wajah lebih sering digunakan karena wajah telah terbukti unik, akurat, aman, mudah, dan nyaman untuk dipakai sebagai identifikasi. Dari  percobaan  dan  pengujian  yang  dilakukan.  Alat  dapat mengenali citra wajah menggunakan visual studio 2010 dengan bahasa C# dan XML sebagai database penyimpanan datanya  menggunakan metode gabor wavelet dengan tingkat keberhasilan sampai 90%. Hal ini membuktikan alat ini cukup baik dalam peruses identifikasi wajah.  Kata Kunci : Gabor Wavelet., Face Datection, Face Recognition.  	"Sistem keamanan penitipan barang yang banyak dijumpai hanya menggunakan ID card untuk mengambil barang titipan. Apabila kartu pengenal disalah-gunakan oleh pihak lain maka akan merugikan konsumen jasa penitipan barang. Oleh karena itu perlu dikembangkan rancang bangun sistem penyimpanan dan pengambilan barang titipan berdasarkan password dan pengenalan wajah pemilik. Proses penyimpanan dan pengambilan barang titipan melibatkan penggunaan password dengan sebuah kata kunci dan sistem pengolahan citra pengenal wajah dengan metode Triangle Face. Metode ini  merupakan metode untuk membandingkan jarak mata, hidung dan mulut seseorang dengan satuan piksel. Sistem ini menggunakan sebuah Personal Computer, kamera Webcam, microcontroller, serial komunikasi interface K-125R, driver solenoid dan empat buah loker. Sistem mulai bekerja ketika seseorang melakukan pengambilan citra wajah, kemudian memasukan sebuah password dengan keyboard PC. Apabila benar, maka data akan mengirim ke microcontroller melalui serial dan memerintahkan untuk membuka loker secara otomatis. Dalam penerapan sistem ini cukup aman, karena tingkat keakuratannya 90% dan 10% gagal.   
		Kata Kunci : Teknologi Biometrik, Pengolahan Citra, Triangle Face "	"Dibandingkan dengan kartu identitas yang dimiliki seseorang, memalsukan wajah akan menjadi jauh lebih sulit dibandingkan dengan memalsukan kartu identitas. Oleh karena itu, identifikasi menggunakan pengenalan wajah dengan akurat dan cepat butuh diterapkan, baik untuk meningkatkan keamanan maupun sekedar memudahkan dalam pengidentifikasian seseorang. Face recognition merupakan sebuah proses mengenali wajah dari seseorang yang sebelumnya sudah tersimpan dalam database/sudah dipelajari sebelumnya. Salah satu metode yang cukup terkenal ialah metode Haar dan LBP (Local Binary Pattern).Augmented reality ialah sebuah cara untuk menyisipkan entitas-entitas yang seharusnya hanya ada pada dunia digital menjadi seakan ada pada dunia nyata. Augmented reality sering digunakan untuk tujuan hiburan, informasional, monitoring, dan lain lain. Penelitian ini berfokus pada pembuatan protoype perangkat lunak augmented reality berbasis pendeteksian wajah dengan metode Haar dan LBP serta pengenalan wajah dengan menggunakan metode LBP. Prototype ini dikembangkan pada smartphone Android.  
		Kata Kunci— deteksi wajah, pengenalan wajah, Haar, LBP, Android. "	"RSA merupakan salah satu algoritma kriptografi asimetris yang menggunakan sepasang kunci, yaitu kunci publik dan kunci pribadi. Panjang kunci dapat diatur, dimana semakin panjang bit pembentukan kunci maka semakin sukar untuk dipecahkan karena sulitnya memfaktorkan dua bilangan yang sangat besar. Penelitian ini menerapkan algoritma RSA untuk enkripsi dan dekripsi kolom suatu tabel pada basis data Oracle sebagai basis data terbaik pada saat penulisan ini dibuat. Berdasarkan penelitian yang telah dilakukan, penulis dapat menarik kesimpulan, yaitu: Algoritma kriptografi asimetris RSA dapat diimplementasikan untuk proses enkripsi dan dekripsi kolom suatu tabel pada basis data Oracle, khususnya untuk tipe data varchar2.
		Kata Kunci : kriptografi, enkripsi, RSA, oracle."	"Database saat ini sudah sangat dikenal sebagai media penyimpanan data- data, baik yang bersifat publik maupun data-data yang bersifat personal. Banyaknya pengguna database, membuat data yang ada di dalam database itu sendiri dapat dengan mudah diakses oleh pengguna-pengguna yang tidak memiliki hak akses untuk itu. Demi menciptakan keamanan untuk datadata yang bersifat personal, DBMS menciptakan sebuah sistem keamanan tersendiri.  Penelitian ini bertujuan untuk membangun sebuah aplikasi  yang dapat menggantikan sistem keamanan dari DBMS itu sendiri terkhusus DBMS Mysql dengan menggunakan algoritma kriptografi Affine Cipher yang mudah dan cepat. Metodologi penelitian yang dilakukan meliputi studi pustaka serta pengembangan sistem menggunakan metode Rapid Application Development (RAD).  Studi  pustaka  dilakukan  dengan  cara  mengumpulkan  data-data  dari uraian-uraian teoritis, dan untuk mengimplementasikan rancangan digunakan   pemrograman Java. Hasil dari penelitian ini merupakan Aplikasi Enkripsi dan Dekripsi record- record DBMS Mysql yang dapat memudahkan pengguna dalam mengamankan informasi-informasi  yang ada di dalam database Mysql dari pihak yang tidak diinginkan serta dapat mengembalikan database Mysql kembali ke dalam bentuk aslinya.  
		Keyword : Keamanan Database, Affine Cipher, Mysql, Java"	"Kemajuan teknologi komputer dan telekomunikasi sebagai pisau bermata dua. Di satu sisi kita disederhanakan oleh teknolog, namun pada aspek lain dari kejahatan dengan menggunakan teknologi ini juga meningkat. Keamanan data pada lalu lintas jaringan adalah hal yang diinginkan setiap orang. Algoritma El-Gamal digunakan untuk mengenkripsi tanda tangan digital. Keamanan algoritma El-Gamal terletak pada sulitnya menghitung logaritma bila jumlah yang dipilih adalah bilangan prima besar. Dalam algoritma kriptografi El-Gamal termasuk dalam algoritma asimetris. Algoritma ini memiliki kunci publik terdiri dari angka dan kunci rahasia yang terdiri dari sebuah angka. Salah satu software yang bisa digunakan untuk mengenkripsi data menggunakan algoritma GnuPG ElGamal.
		Kata kunci: Keamanan Data, Kriptografi, El Gamal, GnuPG"	"Salah satu sistem keamanan komputer yang sedang menjadi kebutuhan masyarakat adalah sistem keamanan komputer dengan menggunakan sidik jari. Teknologi ini dapat dibilang cukup untuk melindungi informasi yang penting, karena setiap manusia memiliki sidik jari yang berbeda-beda / unik. Penggunaan identifikasi seseorang menggunakan sidik jari pada fingerprint reading, retina mata pada retina scan, dan lainnya tidak lain adalah untuk menjaga keamanan suatu tempat atau benda. Penggunaan anggota tubuh sebagai input untuk identifikasi seseorang dalam keamanan disebut penggunaan sistem biometric. Keluaran dari sistem pencitraan sidik jari adalah berupa sebuah image. Image ini tidak langsung digunakan sebagai kunci, namun dikonversi dulu menjadi sebuah graf berbobot yang masing-masing node-nya memiliki “berat” masing-masing. “Berat” inilah yang menurut rancangan pada makalah ini, digunakan sebagai kunci untuk enkripsi dan dekripsi.
		Kata Kunci : Sidik, Jari, Keamanan, Biometrik
		"	"Kriptografi merupakan salah satu solusi atau metode pengamanan data yang tepat untuk menjaga kerahasiaan dan keaslian data, serta dapat meningkatkan aspek keamanan suatu data atau informasi. Metode ini bertujuan agar informasi yang bersifat rahasia dan dikirim melalui suatu jaringan, seperti LAN atau Internet, tidak dapat diketahui atau dimanfaatkan oleh orang atau pihak yang tidak berkepentingan. Kriptografi mendukung kebutuhan dua aspek keamanan informasi, yaitu perlindungan terhadap kerahasiaan data informasi dan perlindungan terhadap pemalsuan dan pengubahan informasi yang tidak diinginkan. AES-Rinjdael merupakan salah satu algoritma kriptografi yang digunakan dalam mengamankan pesan menggunakan panjang kunci sampai 256 bit, yang mana untuk meghindari kriptanalisis, maka dilakukan metode kombinasi  dengan algoritma  Eliptic Curve Criptografi (ECC) dalam pengenkripsian pesan.
		Keywords—KriptografI, ECC, AES-RINJDAEL"	Keamanan komputer merupakan tindakan pencegahan dari serangan pengguna komputer atau pengakses jaringan yang tidak bertanggung jawab (D.Howard, 1997). Dengan adanya keamanan  komputer dapat mencegah tindak  kejahatan dalam bidang komputer. Salah satu metode keamanan komputer yaitu dengan menggunakan Algoritma Message Digest 5 untuk keaman LHS dengan menerapkan MD5 file dapat di enkripsi dan didekripsi oleh user. Dengan menggunakan metode algoritma missage digest 5 yang mempunyai fungsi hash (prosedur terdefinisi atau fungsi matematika yang mengubah variabel dari suatu data yang berukuran besar menjadi lebih sederhana) kriptografi yang digunakan secara luas dengan hash value 128-bit. MD5 dimanfaatkan dalam berbagai aplikasi keamanan, dan umumnya digunakan untuk menguji integritas sebuah file. Tujuan dari penelitian ini diharapkan informasi dari LHS tersebut dapat terjaga dengan baik tanpa dapat dimanipulasi oleh orang lain untuk merusak informasi yang ada. Dengan adanya aplikasi keamanan LHS menggunakan algoritma MD5 diharapakan dapat mempermudah mahasiswa, pertama dengan adanya sistem keamanan LHS pada Fakultas Teknik Universitas Muhammadiyah Bengkulu ini informasi keaslian LHS tidak dapat dimanipulasi oleh pihak lain. Kedua, dengan adanya aplikasi keamanan ini dapat mempermudah mahasiswa dalam melihat lembar hasil studi mereka. Kata Kunci : Kriptografi, Enkripsi, Dekripsi, MD5	"Semakin meningkatnya perkembangan komunikasi data membuat semakin pentingnya aspek keamanan dan kerahasiaan data. Kriptografi merupakan suatu seni atau ilmu menjaga keamanan data atau pesan yang bersifat mengacak suatu data atau pesan. Sedangkan steganografi adalah ilmu menyembunyikan pesan atau data ke dalam suatu media. Kedua teknik tersebut dapat digabungkan dan akan menghasilkan suatu sistem keamanan data yang tinggi. Pada penelitian ini, terlebih dahulu dilakukan proses enkripsi data atau pesan rahasia yang berupa data teks angka dengan jumlah maksimum yang dimasukkan adalah 24 digit angka, kemudian hasil enkripsi (ciphertext) akan disembunyikan ke dalam suatu file gambar yang berformat bitmap dengan ukuran minimum 25x25. Selanjutnya, dilakukan proses ekstraksi dan dekripsi ciphertext, sehingga diperoleh kembali plaintext yang berupa data teks angka. Algoritma kriptografi yang digunakan adalah algoritma Rabin Public Key dan teknik steganografi yang digunakan adalah metode End of File.   
		Kata kunci— Keamanan Data, End of File, Enkripsi, Dekripsi, Rabin Public Key. "

	}

$HardwareSoftware = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$SistemInformasi = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$DataMining = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$InteraksiManusia dengan Komputer = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$KecerdasanBuatan = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$ECommerce = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$CustomerRelationship Management = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$Game = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$Animation = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$BigData = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$EBisnis = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$KomputerGrafis = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$Bioinformatika = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$MachineLearning = array();
	foreach ($variable as $key => $value) {
		# code...
	}

$Robot = array();
	foreach ($variable as $key => $value) {
		# code...
	}


?>
